### ISSUE TITLE
callout (.conum) missing for asciidoc

### ISSUE THREAD

**Issue by ghost** [reitzig/today-i-learned#5]
Hello,

I love your project!

Your script does not extract the .conum classes for proper font callout asciidoc rendering from the original asciidoc css.

Is this project closed or do you want to continue?

Thanks,

f-s

**Comment by ghost** [comment]
Probably something like this missing:

```css
.conum { display: inline-block; color: white !important; background-color: #333333; -webkit-border-radius: 100px; border-radius: 100px; text-align: center; width: 20px; height: 20px; font-size: 12px; font-weight: bold; line-height: 20px; font-family: Arial, sans-serif; font-style: normal; position: relative; top: -2px; letter-spacing: -1px; }
.conum * { color: white !important; }
.conum + b { display: none; }
.conum:after { content: attr(data-value); }
.conum:not([data-value]):empty { display: none; }

.colist>table tr>td:first-of-type{ border:0; min-width:0; padding:0 .75em;}
.colist>table tr>td:last-of-type{ border:0; min-width:0; padding:.25em 0}
.colist>table tr:nth-child(even) { background:0 0 }
```
